[tox]
envlist = py310, py311, py312, py313, py314

[testenv]
deps = -r requirements-dev.txt
setenv =
    EDITOR = editor
commands =
    python -m pytest {posargs}

[testenv:coverage]
package = editable
base_python = 3.14
commands =
    coverage run -m pytest {posargs}
    coverage xml
    coverage html
    coverage report

[testenv:pre-commit]
package = skip
base_python = 3.14
deps =
    pre-commit
    pre-commit-uv
commands =
    pre-commit run --all-files

[pytest]
testpaths =
    tests
