name: pre-commit

on:
  pull_request:
  push:
    branches:
    - main
    - test-me-*
    tags:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Install pre-commit
      run: uv tool install pre-commit --with pre-commit-uv
    - name: Install hooks
      run: uv tool run pre-commit install-hooks
    - name: Run pre-commit
      run: uv tool run pre-commit run --all-files
