name: pre-commit

on:
  pull_request:
  push:
    branches:
    - main
    - test-me-*
    tags:
    - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tox-dev/action-pre-commit-uv@v1
