name: tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    - test-me-*
    tags:
    - '*'

jobs:
  build:
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv python list --only-installed
        uv tool install tox --with tox-uv
    - name: Test with tox for ${{ matrix.python-version }}
      run: uv tool run tox -e py
